# ZIPs and publishes a new release to Chrome Web Store & Firefox Add-ons

name: Publish

on:
  release:
    branches: [main]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build production code from source code and zips it
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # get dependencies
      - run: npm ci
      # build code
      - run: npm run build
      # zip files
      - name: create zip file
        uses: thedoctor0/zip-release@master
        with:
          path: "./dist"
          filename: "release.zip"
      # save zip file
      - name: save zip file
        uses: actions/upload-artifact@v2
        with:
          name: REL-release
          path: release.zip
  add-to-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get zip file
        uses: actions/download-artifact@v2
        with:
          name: REL-release
      - run: echo "test"
      - run: ls
  publish-CWS:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  publish-FFA:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
