# ZIPs and publishes a new release to Chrome Web Store & Firefox Add-ons

name: Publish

on:
  release:
    branches: [main]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build production code from source code and zips it
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # get dependencies
      - run: npm ci
      # build code
      - run: npm run build
      # zip files
      - name: create zip file
        uses: thedoctor0/zip-release@master
        with:
          path: "./dist"
          filename: "release.zip"
      # # generate XPI for Firefox addons
      # - name: "web-ext build"
      #   id: web-ext-build
      #   uses: kewisch/action-web-ext@v1
      #   with:
      #     cmd: build
      #     source: dist
      # - name: "save xpi"
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: REL-xpi
      #     path: ${{ steps.web-ext-build.outputs.target }}
      # save manifest file
      - name: save manifest file
        uses: actions/upload-artifact@v2
        with:
          name: REL-manifest
          path: dist/manifest.json
      # save zip file
      - name: save zip file
        uses: actions/upload-artifact@v2
        with:
          name: REL-release
          path: release.zip
  publish-CWS:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get zip file
        uses: actions/download-artifact@v2
        with:
          name: REL-release
      - uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: "${{ secrets.GOOGLE_refreshToken }}"
          client-id: "${{ secrets.GOOGLE_clientId }}"
          client-secret: "${{ secrets.GOOGLE_clientSecret }}"
          file-name: "./release.zip"
          app-id: "lfjohnbbhhoecemedkgheejgclolojmi"
          publish: true
  publish-FFA:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get zip file
        uses: actions/download-artifact@v2
        with:
          name: REL-release
      # - name: Get xpi file
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: REL-xpi
      - name: Get manifest file
        uses: actions/download-artifact@v2
        with:
          name: REL-manifest
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: "{22e2863f-abc1-4c3e-81ec-8fbf8db0858f}"
          xpi: release.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
